server:
  port: 8080

spring:
  application:
    name: bellboy-service-template

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pixid
    username: pramods
    password: User@123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA:public}
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    schemas: ${DATABASE_SCHEMA:public}
    baseline-on-migrate: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 5
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
            isClustered: true
          dataSource:
            quartzDataSource:
              provider: hikari
              driverClassName: org.postgresql.Driver
              jdbcUrl: jdbc:postgresql://localhost:5432/pixid
              username: pramods
              password: User@123
              maximumPoolSize: 5

# Service configuration / env
template-service:
  environment: ${ENVIRONMENT:dev}
